name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix: 
    #     go: ["1.14","1.15"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          # go-version: ${{ matrix.go }}
          go-version: 1.15
      - run: go test
      - run: go run math.go

      - name: Setup up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: deividroger/integracao-continuav2:latest
          